### ISSUE TITLE
присоединяйте (link) к задачам pull request

### ISSUE THREAD

**Issue by Vaysman** [i-wanna-be-a-programmer/wbz-api#11]
Это поможет вам понять, что именно было сделано для issue.
Это можно сделать в меню **Linked pull reuests**
![image](https://user-images.githubusercontent.com/78981/108199247-006bff00-711d-11eb-80f4-c6eb9ee6c61c.png)

**Comment by Fr0z3Nn** [comment]
Принято. Изначально думал об этой идеи, но из-за неправильной организации не получилось. Организацию исправил, теперь будем делать именно так.
