### ISSUE TITLE
Add ToDo

### ISSUE THREAD

**Issue by serjan-nasredin** [i-wanna-be-a-programmer/wbz-api#26]
Create a list. Don't write a list in the problem item.

```
ToDo.txt
```

**Comment by Fr0z3Nn** [comment]
Не совсем понятно, можно поподробнее?

**Comment by serjan-nasredin** [comment]
Список дел. Позволяет видеть прогресс проекта. Пример того, что могло бы туда попасть: 

```
    написать тесты
```

Но конечно, дело ваше.

**Comment by Fr0z3Nn** [comment]
интересно, надо ознакомиться
