### ISSUE TITLE
создать список задач необходимых для выпуска минимальной функциональной версии

### ISSUE THREAD

**Issue by Vaysman** [i-wanna-be-a-programmer/wbz-api#6]
* каждая задача - это отдельная issue
* каждая задача имеет описание, которое необходимо для ее выполнения
* каждая задача имеет условия (приемочные тесты), которые позволяют определить, что задача выполнена
* создать несколько вех (milestone) с датами и распределить задачи в них

**Comment by Vaysman** [comment]
@i-wanna-be-a-programmer/team-wbz-api где можно посмотреть список?

**Comment by Fr0z3Nn** [comment]
> @i-wanna-be-a-programmer/team-wbz-api где можно посмотреть список?

Список отображается в мильстоунах при нажатии на них
